services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-container
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis-cache:
    image: redis:7-alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - app-network

  user-service:
    build: .
    container_name: user-service-container
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://postgres-db:5432/${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST_NAME}
      - REDIS_PORT=${REDIS_PORT_NUMBER}
    depends_on:
      - postgres-db
      - redis-cache
    networks:
      - app-network

  sonarqube:
    image: sonarqube:10.4-community
    container_name: sonarqube-container
    ports:
      - "9000:9000"
    networks:
      - app-network


volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
